export enum pages {
  MY_ORDER = "my-order",
  SHOP = "shop",
  OUR_STORY = "our-story",
  PRESS = "press",
  OUR_INGREDIENTS = "our-ingredients",
  WISHLIST = "wishlist",
  STORE_LOCATOR = "store-locator",
  TRACK_YOUR_ORDER = "track-your-order",
  CONTACT_US = "contact-us",
  FAQ = "faqs",
  BLOG = "blog",
  CSR_Policy = "csr-policy",
  PRIVACY_POLICY = "privacy-policy",
  APRIL_OFFERS_TERMS_AND_CONDITION = "april-offers-tc",
  MONEY_BACK_GUARANTEE = "money-back-guarantee",
  TERMS_AND_CONDITIONS = "terms-conditions",
  RETURN_POLICY = "return-policy",
  LOGIN = "login",
  CASHBACKS = "cashbacks",
  TERMS_AND_CONDITIONS_CASHBACK = "terms-and-conditions-cashaback",
  INFLUENCER_SIGNUP = "influencer-signup",
  ABOUTUS = "about-us",
  SUBSCRIPTIONS = "subscriptions",
  COMPANY = "company",
  BUYER_DISPATCH = "buyer-dispatch",
  BUYER_ORDER = "buyer-order",
  SUPPLIER_DISPATCH = "supplier-dispatch",
  SUPPLIER_ORDER = "supplier-order",
  SELECT_CATEGORY = "select-category",
  TEAM_MEMBER = "team-member",
  HORECA = "horeca",
  RECIPES = "recipes",
  RETURNS_AND_REFUNDS = "returns-refund",
  SWA_STORY = "swa-story",
  WHY_PLIX = "why-plix",
  Membership = "membership",
  PLIX_CLEAN_LABEL_CERTIFIED = "clean-label-certified",
  PLIX_PLANT_A_TREE = "pledge-a-tree",
  PLIX_SALES_PAGE2 = "plix-flashsale",
  PLIX_SALES_PAGE3 = "valentines-sale",
  PLIX_SALES_PAGE4 = "jeet",
  WHY_BODYFIRST = "why-bodyfirst",
  PLIX_SALES_PAGE = "flash-sale",
  REFUND_AND_CANCELLATION = "refund-and-cancellation",
  GUIDANCE = "guidance",
  CONSULTATION_FORM = "consultation-form",
  NUTRITION_FORM = "nutrition-form",
  AUTHENTICITY = 'authenticity',
  BUG_REPORT = 'report-a-bug',
  OTP_OUT = 'opt-out',
  OTP_IN = 'opt-in',
  BUILD_YOUR_BOX = 'build-your-box',
  BUILD_YOUR_BOX_2 = 'build-your-box-2',
  BUILD_YOUR_BOX_3 = 'build-your-box-3',
  BULD_YOUR_BOX_3_NEW = 'build-your-box-3-new',
  BUILD_YOUR_BOX_4 = 'build-your-box-4',
  BUILD_YOUR_BOX_5 = 'build-your-box-5',
  BUILD_YOUR_BOX_PERFUME_BOX_3 = "build-your-box-perfume-gift-3",
  GIFT_BOX = "gift-box",
  GIFT_BOX_GALLERY = "gift-box-gallery",
  PATCH_TEST = "patch-test",
  QUIZ = 'quiz',
  QUIZNEW= 'quiz-new',
  QUIZSKIN = 'quiz-skin-care',
  QUIZSKINRESULTS = 'quiz-skin-results',
  QUIZ_WIDGET = 'quiz-widget',
  QUIZ_WEIGHT_LOSS = 'quiz-weight-loss',
  QUIZ_WEIGHT_LOSS_RESULT = 'quiz-result',
  QUIZ_SKIN_LANDING_PAGE = 'skin-quiz-landing-page',
  QUIZ_HAIR_MALE_LANDING_PAGE = 'quiz-hair-loss-male',
  QUIZ_HAIR_FEMALE_LANDING_PAGE = 'quiz-hair-loss-female',
  QUIZHAIR = 'quiz-hair-loss',
  QUIZ_HAIR_MALE_RESULTS = 'quiz-hair-male-results',
  QUIZ_HAIR_FEMALE_RESULTS = 'quiz-hair-female-results',
  GOOGLE_FORM_PAGE = 'plix-form',
  GIFTING = 'gifting',
  BUILD_YOUR_BOX_GALLERY = 'build-your-box-gallery',
  BXGY_PAGE ='bxgy',
  DIET_PLAN_REDIRECTION = 'diet-plan',
}

export const byobPages = ['build-your-box','build-your-box-2', 'build-your-box-3', 'build-your-box-5', 'build-your-box-4', 'gift-box', 'build-your-box-3-new', 'build-your-box-perfume-gift-3', 'gift-box-gallery'];


export enum clients {
  ARAKUCOFFEE = "arakucoffee",
  DEMO = "demo",
  DRINKWA_STAGE = "drinkswa-stage",
  DRINKSWA2 = "drinkswa2",
  IKKAI = "ikkai",
  LOTUS = "lotus",
  LOTUS_NEW = "lotus-new",
  LOTUS_STAGE = "lotus-stage",
  PLIXLIFE = "plixlife",
  PLIXLIFEFC = "plixlifefc",
  SAFARI = "safari",
  YARNBAZAR = "yarnbazar",
  MPIL = 'mpil',
  GENIEFC = "geniefc",
  WOW_HEALTH_NEW = "wowhealth-new",
  WOWFC_NEW = "wowfc-new",
  BODY_FIRST = "body-first",
  BUY_WOW = "buywow"
 
}


