export { default as RupeesDiscounted } from "./RupeesDiscounted";
export { default as RupeesUndiscounted } from "./RupeesUndiscounted";
export { default as QuantityDecrease } from "./QuantityDecrease";
export { default as QuantityIncrease } from "./QuantityIncrease";
export { default as OOSBox } from "./OOSBox";
export * from "./RatingEmojis";
export { default as OrderConfirmed } from "./OrderConfirmed";
// export { default as CashbackRupees } from "./CashbackRupees";
export { default as GoBackArrow } from "./GoBackArrow";
export { default as SavingsRupees } from "./SavingsRupees";
export { default as GTCArrow } from "./GTCArrow";
export { default as RightChevron } from "./RightChevron";
export { default as AccountIcon } from "./AccountIcon";
export { default as Truck } from "./Truck";
export { default as Shop } from "./Shop";
export { default as ByConcern } from "./ByConcern";
export { default as FunCombos } from "./FunCombos";
export { default as SaleBox } from "./SaleBox";
export { default as ArrowUp } from "./ArrowUp";
export { default as DoubleArrow } from "./DoubleArrow";
